// rounding mode.
// ====

CxingMathBinding(feRndMode)
CxingMathBinding(feRndMode_manual)
CxingMathBinding(feRndMode_auto)

// mandatory operations not expressed as operators
// ====

// arithmetic
CxingMathBinding(sqrt)
CxingMathBinding(fma)
CxingMathBinding(fabs)
CxingMathBinding(copysign)

// relations
CxingMathBinding(fmax)
CxingMathBinding(fmin)
CxingMathBinding(fpmax)
CxingMathBinding(fpmin)

// conversion
CxingMathBinding(dtoa)
CxingMathBinding(atod)

// classification
CxingMathBinding(fpclassify)
CxingMathBinding(isfinite)
CxingMathBinding(isinf)
CxingMathBinding(isnan)
CxingMathBinding(isnormal)
CxingMathBinding(signbit)

// exponent manipulation
CxingMathBinding(ilogb)
CxingMathBinding(scalbn)

// rounding to integers:
CxingMathBinding(ceil)
CxingMathBinding(floor)
CxingMathBinding(trunc)
CxingMathBinding(round)
CxingMathBinding(roundeven)
CxingMathBinding(rint)

// recommended operations provided to applications on best-effort basis
// ====

CxingMathBinding(sin)
CxingMathBinding(cos)
CxingMathBinding(tan)
CxingMathBinding(sinpi)
CxingMathBinding(cospi)
CxingMathBinding(tanpi)

CxingMathBinding(asin)
CxingMathBinding(acos)
CxingMathBinding(atan)
CxingMathBinding(atan2)
CxingMathBinding(asinpi)
CxingMathBinding(acospi)
CxingMathBinding(atanpi)
CxingMathBinding(atan2pi)

CxingMathBinding(sinh)
CxingMathBinding(cosh)
CxingMathBinding(tanh)
CxingMathBinding(asinh)
CxingMathBinding(acosh)
CxingMathBinding(atanh)

CxingMathBinding(exp)
CxingMathBinding(exp2)
CxingMathBinding(exp10)
CxingMathBinding(expm1)
CxingMathBinding(exp2m1)
CxingMathBinding(exp10m1)

CxingMathBinding(log)
CxingMathBinding(log2)
CxingMathBinding(log10)
CxingMathBinding(logp1)
CxingMathBinding(log1p)
CxingMathBinding(log2p1)
CxingMathBinding(log10p1)

CxingMathBinding(cbrt)
CxingMathBinding(compoundn)
CxingMathBinding(hypot)
CxingMathBinding(pow)
CxingMathBinding(pown)
CxingMathBinding(powr)
CxingMathBinding(rootn)
CxingMathBinding(rsqrt)

CxingMathConstants(HUGE_VAL)
CxingMathConstants(INFINITY)
CxingMathConstants(NAN)

CxingMathConstants(M_E)
CxingMathConstants(M_LOG2E)
CxingMathConstants(M_LOG10E)
CxingMathConstants(M_LN2)
CxingMathConstants(M_LN10)

CxingMathConstants(M_PI)
CxingMathConstants(M_PI_2)
CxingMathConstants(M_PI_4)
CxingMathConstants(M_1_PI)
CxingMathConstants(M_2_PI)

CxingMathConstants(M_2_SQRTPI)
CxingMathConstants(M_SQRT2)
CxingMathConstants(M_SQRT1_2)

CxingMathEnums(FP_NORMAL)
CxingMathEnums(FP_SUBNORMAL)
CxingMathEnums(FP_ZERO)
CxingMathEnums(FP_INFINITE)
CxingMathEnums(FP_NAN)