/* Auto-generated by "utils/grammar2rules.py". May be adapted. */
#ifndef dcc_ppexpr_grammar_h
#define dcc_ppexpr_grammar_h 1
#include "../lalr-common/lalr.h"
extern strvec_t *ns_rules_ppexpr;
#define hRule(s) strvec_str2i(ns_rules_ppexpr, s)
void *goal_pp_const_expr(lalr_rule_params);
void *ident_ident(lalr_rule_params);
void *const_true(lalr_rule_params);
void *const_false(lalr_rule_params);
void *const_null(lalr_rule_params);
void *const_binlit(lalr_rule_params);
void *const_declit(lalr_rule_params);
void *const_octlit(lalr_rule_params);
void *const_hexlit(lalr_rule_params);
void *const_decfplit(lalr_rule_params);
void *const_hexfplit(lalr_rule_params);
void *const_charlit(lalr_rule_params);
void *const_strlit(lalr_rule_params);
void *primary_paren(lalr_rule_params);
void *primary_ident(lalr_rule_params);
void *primary_const(lalr_rule_params);
void *postfix_degenerate(lalr_rule_params);
void *unary_degenerate(lalr_rule_params);
void *unary_positive(lalr_rule_params);
void *unary_negative(lalr_rule_params);
void *unary_bitcompl(lalr_rule_params);
void *unary_logicnot(lalr_rule_params);
void *mulexpr_degenerate(lalr_rule_params);
void *mulexpr_multiply(lalr_rule_params);
void *mulexpr_divide(lalr_rule_params);
void *mulexpr_remainder(lalr_rule_params);
void *addexpr_degenerate(lalr_rule_params);
void *addexpr_add(lalr_rule_params);
void *addexpr_subtract(lalr_rule_params);
void *shiftexpr_degenerate(lalr_rule_params);
void *shiftexpr_lshift(lalr_rule_params);
void *shiftexpr_rshift(lalr_rule_params);
void *relops_degenerate(lalr_rule_params);
void *relops_lt(lalr_rule_params);
void *relops_gt(lalr_rule_params);
void *relops_le(lalr_rule_params);
void *relops_ge(lalr_rule_params);
void *eqops_degenerate(lalr_rule_params);
void *eqops_eq(lalr_rule_params);
void *eqops_ne(lalr_rule_params);
void *bitand_degenerate(lalr_rule_params);
void *bitand_bitand(lalr_rule_params);
void *bitxor_degenerate(lalr_rule_params);
void *bitxor_bitxor(lalr_rule_params);
void *bitor_degenerate(lalr_rule_params);
void *bitor_bitor(lalr_rule_params);
void *logicand_degenerate(lalr_rule_params);
void *logicand_logicand(lalr_rule_params);
void *logicor_degenerate(lalr_rule_params);
void *logicor_logicor(lalr_rule_params);
void *tenary_degenerate(lalr_rule_params);
void *tenary_tenary(lalr_rule_params);
void *assignment_degenerate(lalr_rule_params);
void *exprlist_degenerate(lalr_rule_params);
void *exprlist_exprlist(lalr_rule_params);
extern lalr_rule_t ppexpr_grammar_rules[];
#endif /* dcc_ppexpr_grammar_h */
