/* Auto-generated by "utils/grammar2rules.py". May be adapted. */
#ifndef dcc_ppexpr_grammar_h
#define dcc_ppexpr_grammar_h 1
#include "../lalr-common/lalr.h"
extern strvec_t *ns_rules_ppexpr;
#define hRule(s) strvec_str2i(ns_rules_ppexpr, s)
void *pp_goal_pp_const_expr(lalr_rule_params);
void *pp_ident_ident(lalr_rule_params);
void *pp_const_true(lalr_rule_params);
void *pp_const_false(lalr_rule_params);
void *pp_const_null(lalr_rule_params);
void *pp_const_binlit(lalr_rule_params);
void *pp_const_declit(lalr_rule_params);
void *pp_const_octlit(lalr_rule_params);
void *pp_const_hexlit(lalr_rule_params);
void *pp_const_decfplit(lalr_rule_params);
void *pp_const_hexfplit(lalr_rule_params);
void *pp_const_charlit(lalr_rule_params);
void *pp_const_strlit(lalr_rule_params);
void *pp_primary_paren(lalr_rule_params);
void *pp_primary_ident(lalr_rule_params);
void *pp_primary_const(lalr_rule_params);
void *pp_postfix_degenerate(lalr_rule_params);
void *pp_unary_degenerate(lalr_rule_params);
void *pp_unary_positive(lalr_rule_params);
void *pp_unary_negative(lalr_rule_params);
void *pp_unary_bitcompl(lalr_rule_params);
void *pp_unary_logicnot(lalr_rule_params);
void *pp_mulexpr_degenerate(lalr_rule_params);
void *pp_mulexpr_multiply(lalr_rule_params);
void *pp_mulexpr_divide(lalr_rule_params);
void *pp_mulexpr_remainder(lalr_rule_params);
void *pp_addexpr_degenerate(lalr_rule_params);
void *pp_addexpr_add(lalr_rule_params);
void *pp_addexpr_subtract(lalr_rule_params);
void *pp_shiftexpr_degenerate(lalr_rule_params);
void *pp_shiftexpr_lshift(lalr_rule_params);
void *pp_shiftexpr_rshift(lalr_rule_params);
void *pp_relops_degenerate(lalr_rule_params);
void *pp_relops_lt(lalr_rule_params);
void *pp_relops_gt(lalr_rule_params);
void *pp_relops_le(lalr_rule_params);
void *pp_relops_ge(lalr_rule_params);
void *pp_eqops_degenerate(lalr_rule_params);
void *pp_eqops_eq(lalr_rule_params);
void *pp_eqops_ne(lalr_rule_params);
void *pp_bitand_degenerate(lalr_rule_params);
void *pp_bitand_bitand(lalr_rule_params);
void *pp_bitxor_degenerate(lalr_rule_params);
void *pp_bitxor_bitxor(lalr_rule_params);
void *pp_bitor_degenerate(lalr_rule_params);
void *pp_bitor_bitor(lalr_rule_params);
void *pp_logicand_degenerate(lalr_rule_params);
void *pp_logicand_logicand(lalr_rule_params);
void *pp_logicor_degenerate(lalr_rule_params);
void *pp_logicor_logicor(lalr_rule_params);
void *pp_tenary_degenerate(lalr_rule_params);
void *pp_tenary_tenary(lalr_rule_params);
void *pp_assignment_degenerate(lalr_rule_params);
void *pp_exprlist_degenerate(lalr_rule_params);
void *pp_exprlist_exprlist(lalr_rule_params);
extern lalr_rule_t ppexpr_grammar_rules[];
#endif /* dcc_ppexpr_grammar_h */
